version: "3"
services:
  client:
    image: "node:12"
    working_dir: /usr/src/app
    ports:
    - 3030:3030
    volumes:
    - ./client:/usr/src/app
    links:
    - server
    command: yarn start:dev
  server:
    build: ./server/
    volumes: 
    - ./server:/go/usr/server
    ports:
    - 8080:8080
    links:
    - redis
    tty:
      true
  worker:
    build: ./worker/
    volumes: 
    - ./worker:/go/usr/worker
    links:
    - redis
    tty:
      true
  redis:
    image: redis