root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./server ."
bin = "./server"
include_ext = ["go"]
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false