root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./worker ."
bin = "./worker"
full_bin = "APP_ENV=dev APP_USER=air ./worker"
include_ext = ["go"]
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false